# Generated by Django 4.2.3 on 2023-07-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jonesapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
