# Generated by Django 4.2.3 on 2023-07-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jonesapp', '0007_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
