# Generated by Django 4.2.3 on 2023-07-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jonesapp', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_img',
        ),
    ]
