# Generated by Django 4.2.3 on 2023-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jonesapp', '0009_delete_upload_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
