# Generated by Django 4.2.3 on 2023-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonesapp', '0012_upload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_video',
            name='clips',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
